[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metabox-sdk = { path = "../../MetaBox-SDK" }
tokio = { version = "1", features = ["full"] }
candid = "0.7.16"
